@startuml

skinparam roundcorner 20
skinparam monochrome true

|XRCE Protocol|
:Receive Topic;
|Serial Transport|
:Receive;
|System|
:Read;
:Device Buffer|
|Serial Transport|
:Unframing;
:Unframing Buffer|
:Append Fragment;
|XRCE Protocol|
:Input Stream Buffer|
:Deserialization;
:Topic<

@enduml
